swagger: "2.0"

info:
  version: 1.0.0
  title: go-musicbot api
  description: A simple API to control a go-musicbot via http.

schemes:
  - http
host: localhost
basePath: /v1

consumes:
  - application/json
  - application/vnd.api+json
  - application/x-www-form-urlencoded

produces:
  - application/json; charset=utf-8
  - application/vnd.api+json

paths:
  /djplus/{yid}:
    parameters:
      - $ref: "#/parameters/yid"
    post:
      summary: "Youtube ripping endpoint"
      description: "This endpoint allows you to add a youtube link to the download queue"
      security: []
      responses:
        200:
          description: "Youtube ID was succesfully added to the download queue"
        404:
          $ref: "#/responses/UnableToDownloadYIDResponse"
        500:
          $ref: "#/responses/Standard500ErrorResponse"

definitions:
  ErrorPointer:
    type: object
    properties:
      pointer:
        type: string
        minLength: 1
        maxLength: 128
  Error:
    type: object
    properties:
      detail:
        type: string
        minLength: 1
        maxLength: 512
      status:
        type: string
        pattern: "^[2345][0-9]{2}$"
        minLength: 3
        maxLength: 3
      source:
        $ref: "#/definitions/ErrorPointer"

responses:
  Standard500ErrorResponse:
    description: "An unexpected error occurred"
    schema:
      $ref: "#/definitions/Error"
  UnableToDownloadYIDResponse:
    description: "Unable to download Youtube ID"

parameters:
  yid:
    name: yid
    in: path
    required: true
    description: "Youtube ID, needs to point to a single video"
    type: string
    pattern: "[a-zA-Z0-9_-]{11}"
    minLength: 11
    maxLength: 11

securityDefinitions:
  UserSecurity:
    type: apiKey
    in: header
    name: X-User-Token

security:
  - UserSecurity: []
