---
irc:
  nickname: "IrcBot"
  server: "irc.mononoke.nl"
  port: 6697
  channel: "#bot-test"
  tls: true
  tls_verify: true
  daemonize: false
  debug: false

bot:
  command_character: "!"
  valid_commands:
    - "dj+"
    - "next"
    - "np"
    - "radio"
  stream_url: "http://radio.as65342.net:8000/2600nl.ogg.m3u"
  radio_messages:
    - "Tired of waiting for DJShuffle?"
    - "Fed up with the ytclient links of berm?"
    - "Cant wait till friday?"
    - "Gaat de meet nog door?"
    - "Feeling lonely?"
    - "Are you missing DJShuffle?"
    - "Did you miss Sjaak?"

youtube:
  music_basedir: "/music"
  downloader: "/usr/local/bin/ytclient-dl"
  seen_file: "/var/spool/fetch_youtube.seen"
  url: "https://www.youtube.com/watch?v="

mpd:
  address: "127.0.0.1"
  port: 6600
  password: ""
